#!/bin/env bash

set -e

export LB_SSH_FLOCK_WAIT=5

source .settings 2>/dev/null || true

[ -z $LB_MACHINESDIR ] && { export LB_MACHINESDIR=$PWD/_machines; }
[ -d $LB_MACHINESDIR ] || { echo "Directory $LB_MACHINESDIR doesnt exist"; exit 1; }
[ -z "$(ls -A $LB_MACHINESDIR)" ] && { echo "Directory $LB_MACHINESDIR is empty"; exit 1; }

export LB_DATADIR=$PWD/_data
mkdir -p $LB_DATADIR

[ -z $LB_SSHSCRIPTSDIR ] && export LB_SSHSCRIPTSDIR=$LB_DATADIR/_ssh_scripts
mkdir -p "$LB_SSHSCRIPTSDIR"

export LB_RUNDATE=$(date +%s)
export LB_LOG=$LB_DATADIR/_meta/$LB_RUNDATE.log

[ -f $LB_LOG ] && {
    echo "Cant run logbuster more often than once in a second"
    exit 1; }

[ $LB_TESTING ] && { export LB_LOG=_testing.log; }

export PATH=$PATH:$PWD/bin

mkdir -p "$(dirname "${LB_LOG}")"
exec > $LB_LOG; exec 2>&1

echo logbuster start "'$@'"

# if $0 name name2 ...
[ -z $1 ] || {
    for LB_MACHINE in ${@}; do
        lb_collect $LB_MACHINE
    done; }

# if no machine name
[ ! -z $1 ] || {
    for LB_MACHINE in $LB_MACHINESDIR/*; do
        LB_MACHINE=$(basename "${LB_MACHINE%.*}")
        [[ ${LB_MACHINE::1} == "_" ]] || {
            lb_collect $LB_MACHINE
        }
    done; }

exit 0
